### ISSUE TITLE
When user input is invalid the uploading gif won't disappear 

### ISSUE THREAD

**Issue by SanskarSh** [Pragmatic-Programmers/chotu-telegram#2]
![telegram](https://user-images.githubusercontent.com/76647896/137754176-9a44545c-6057-43e3-968a-7ee1be9207cc.jpeg)

**Comment by Punit-Choudhary** [comment]
@parnexcodes @SanskarSh could you please fix this issue.

**Comment by Punit-Choudhary** [comment]
Patched by @parnexcodes in #3
